import jwt
token = "eyJhbGciOiJIUzI1NiIsImtpZCI6ImkxMUlyc0FPOHRpTGgwdEkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3ByeWNudWR0a2VxYnJscG9ucnVrLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwYTAwMDIzZC02YTllLTRkZTgtYTMzNy0yMzI5OGFjMjAxODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYyOTM3OTgzLCJpYXQiOjE3NjI5MzQzODMsImVtYWlsIjoiIiwicGhvbmUiOiI5MTcwMjAyOTAyNzciLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJwaG9uZSIsInByb3ZpZGVycyI6WyJwaG9uZSJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiMGEwMDAyM2QtNmE5ZS00ZGU4LWEzMzctMjMyOThhYzIwMTg2In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNzYyOTM0MzgzfV0sInNlc3Npb25faWQiOiJhYWJmYWJlYi1jMmM4LTQ4MmItODRhOC0yZjkwYmUzZTk5YjUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.FeSQI0Aq70Qje9_oIcx9Gx1fOSFSZNXMx1llWbl1cdg"

# decode without verifying signature (just to inspect claims)
payload = jwt.decode(token, options={"verify_signature": False})
print(payload)

